# Generated by Django 5.2.6 on 2025-09-06 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('direccion', models.CharField(blank=True, max_length=256, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('ultimo_login', models.DateTimeField(auto_now=True)),
                ('tipo_usuario', models.CharField(max_length=35)),
            ],
        ),
    ]
