# Generated by Django 5.2.6 on 2025-09-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_medico_alter_usuario_options_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Médico'), ('ADMIN', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista')], max_length=64, unique=True, verbose_name='Nombre del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='Gestion_usu_tipo_us_4d827c_idx',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Gestion.rol', verbose_name='Rol del usuario'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol', 'estado'], name='Gestion_usu_rol_id_e57d1c_idx'),
        ),
    ]
