# Generated by Django 5.2.6 on 2025-09-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_especialidad_medico_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(blank=True, null=True, related_name='medicos', to='Gestion.especialidad', verbose_name='Especialidades médicas'),
        ),
    ]
