# Generated by Django 5.2.6 on 2025-09-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_remove_medico_especialidad_medico_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='Gestion.especialidad', verbose_name='Especialidades médicas'),
        ),
    ]
