# Generated by Django 5.2.6 on 2025-09-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_alter_medico_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('PACIENTE', 'Paciente'), ('MÉDICO', 'Médico'), ('ADMIN', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista')], max_length=64, unique=True, verbose_name='Nombre del rol'),
        ),
    ]
