# Generated by Django 5.2.6 on 2025-09-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_alter_rol_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatologiasO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial de la patología', max_length=120, unique=True)),
                ('alias', models.CharField(blank=True, help_text='Alias o nombres comunes de la patología', max_length=120)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la patología')),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave'), ('CRITICA', 'Critica')], max_length=50)),
                ('estado', models.BooleanField(default=True, help_text='Activo = True, Eliminado = False')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patologia',
                'verbose_name_plural': 'Patologias',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='Gestion_pat_nombre_e68afc_idx'), models.Index(fields=['gravedad'], name='Gestion_pat_graveda_50d808_idx')],
            },
        ),
    ]
