# Generated by Django 5.2.6 on 2025-09-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_patologiaso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia_clinica', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True)),
                ('antecedentes_oculares', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenOcular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agudeza_visual_derecho', models.CharField(blank=True, max_length=10)),
                ('agudeza_visual_izquierdo', models.CharField(blank=True, max_length=10)),
                ('presion_intraocular_derecho', models.FloatField(blank=True, null=True)),
                ('presion_intraocular_izquierdo', models.FloatField(blank=True, null=True)),
                ('diagnostico_ocular', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='Gestion.paciente')),
            ],
        ),
    ]
