# Generated by Django 5.2.6 on 2025-09-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_patologiaso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente_profile', serialize=False, to='Gestion.usuario')),
                ('numero_historia_clinica', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True)),
                ('antecedentes_oculares', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('agudeza_visual_derecho', models.CharField(blank=True, max_length=20)),
                ('agudeza_visual_izquierdo', models.CharField(blank=True, max_length=20)),
                ('presion_ocular_derecho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('presion_ocular_izquierdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(help_text="Descripción legible de la acción (ej: 'médico Pedro eliminó al paciente Juanito')")),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('objeto', models.CharField(blank=True, help_text="Texto corto indicando el objeto afectado (ej: 'Paciente: Juanito (id:4)')", max_length=200, null=True)),
                ('extra', models.JSONField(blank=True, help_text='Información adicional en JSON (opcional)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='Gestion.usuario')),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-timestamp'],
            },
        ),
    ]
