# Generated by Django 5.2.6 on 2025-09-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_patologiaso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente_profile', serialize=False, to='Gestion.usuario')),
                ('numero_historia_clinica', models.CharField(max_length=64, unique=True, verbose_name='Número de historia clínica')),
                ('alergias_medicamentos', models.TextField(blank=True, null=True, verbose_name='Alergias a medicamentos')),
                ('antecedentes_oculares', models.TextField(blank=True, null=True, verbose_name='Antecedentes oftalmológicos')),
                ('agudeza_visual_derecho', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agudeza visual ojo derecho')),
                ('agudeza_visual_izquierdo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agudeza visual ojo izquierdo')),
                ('presion_intraocular_derecho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Presión intraocular ojo derecho')),
                ('presion_intraocular_izquierdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Presión intraocular ojo izquierdo')),
                ('diagnostico_ocular', models.TextField(blank=True, null=True, verbose_name='Diagnóstico ocular')),
                ('estado', models.BooleanField(default=True, help_text='Activo = True, Eliminado = False')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['paciente__nombre'],
                'indexes': [models.Index(fields=['estado'], name='Gestion_pac_estado_b01d53_idx'), models.Index(fields=['numero_historia_clinica'], name='Gestion_pac_numero__999833_idx')],
            },
        ),
    ]
