# Generated by Django 5.2.6 on 2025-09-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='agudeza_visual_derecho',
            field=models.CharField(default='', max_length=10, verbose_name='Agudeza visual ojo derecho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='agudeza_visual_izquierdo',
            field=models.CharField(default=0, max_length=10, verbose_name='Agudeza visual ojo izquierdo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes_oculares',
            field=models.TextField(default='', verbose_name='Antecedentes oftalmológicos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presion_intraocular_derecho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Presión intraocular ojo derecho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presion_intraocular_izquierdo',
            field=models.DecimalField(decimal_places=2, default=12.12, max_digits=5, verbose_name='Presión intraocular ojo izquierdo'),
            preserve_default=False,
        ),
    ]
