# Generated by Django 5.2.6 on 2025-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_paciente_examenocular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenocular',
            name='agudeza_visual_derecho',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examenocular',
            name='agudeza_visual_izquierdo',
            field=models.TextField(blank=True),
        ),
    ]
