# Generated by Django 5.2.6 on 2025-10-02 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_paciente_patologias'),
        ('doctores', '0002_tipo_atencion_bloque_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita_Medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la cita médica')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la cita médica')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de la cita médica')),
                ('estado', models.BooleanField(default=True, help_text='Activo = True, Cancelado = False')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la cita médica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('motivo_cancelacion', models.TextField(blank=True, help_text='Motivo de la cancelación, si aplica')),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='doctores.bloque_horario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_creacion'], name='citas_cita__fecha_c_2fe2c9_idx'), models.Index(fields=['estado'], name='citas_cita__estado_899038_idx')],
            },
        ),
    ]
