# Generated by Django 5.2.6 on 2025-10-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True, verbose_name='Nombre de la especialidad')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medico_profile', serialize=False, to='acounts.usuario')),
                ('numero_colegiado', models.CharField(max_length=64, unique=True, verbose_name='Número de colegiado')),
                ('especialidades', models.ManyToManyField(blank=True, related_name='medicos', to='doctores.especialidad', verbose_name='Especialidades médicas')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['medico__nombre'],
            },
        ),
    ]
