# Generated by Django 5.2.6 on 2025-10-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia_clinica', models.CharField(max_length=64, unique=True)),
                ('alergias', models.TextField(blank=True)),
                ('antecedentes_oculares', models.TextField(blank=True)),
                ('agudeza_visual_derecho', models.CharField(blank=True, max_length=20)),
                ('agudeza_visual_izquierdo', models.CharField(blank=True, max_length=20)),
                ('presion_ocular_derecho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('presion_ocular_izquierdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acounts.usuario')),
            ],
            options={
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='PatologiasO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial de la patología', max_length=120, unique=True)),
                ('alias', models.CharField(blank=True, help_text='Alias o nombres comunes de la patología', max_length=120)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la patología')),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave'), ('CRITICA', 'Critica')], max_length=50)),
                ('estado', models.BooleanField(default=True, help_text='Activo = True, Eliminado = False')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patologia',
                'verbose_name_plural': 'Patologias',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='citas_patol_nombre_2d9114_idx'), models.Index(fields=['gravedad'], name='citas_patol_graveda_41a1ad_idx')],
            },
        ),
    ]
