# Generated by Django 5.2.6 on 2025-10-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='antecedentes_oculares',
        ),
        migrations.AddField(
            model_name='paciente',
            name='patologias',
            field=models.ManyToManyField(blank=True, null=True, related_name='pacientes', to='citas.patologiaso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='agudeza_visual_derecho',
            field=models.CharField(blank=True, help_text='Ejemplo: 20/20', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='agudeza_visual_izquierdo',
            field=models.CharField(blank=True, help_text='Ejemplo: 20/20', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_historia_clinica',
            field=models.CharField(help_text='Ejemplo: HC-2023-0001', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presion_ocular_derecho',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ejemplo: 15.50', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presion_ocular_izquierdo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ejemplo: 15.50', max_digits=5, null=True),
        ),
    ]
