# Generated by Django 5.2.6 on 2025-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_paciente_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='patologias',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='citas.patologiaso'),
        ),
    ]
