# Generated by Django 5.2.6 on 2025-10-01 18:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PACIENTE', 'Paciente'), ('MÉDICO', 'Médico'), ('ADMIN', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista')], max_length=64, unique=True, verbose_name='Nombre del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre completo')),
                ('password', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('ultimo_login', models.DateTimeField(auto_now=True, verbose_name='Último ingreso')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='acounts.rol', verbose_name='Rol del usuario')),
            ],
            options={
                'verbose_name': 'Usuario del sistema',
                'verbose_name_plural': 'Usuarios del sistema',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(help_text="Descripción legible de la acción (ej: 'médico Pedro eliminó al paciente Juanito')")),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('objeto', models.CharField(blank=True, help_text="Texto corto indicando el objeto afectado (ej: 'Paciente: Juanito (id:4)')", max_length=200, null=True)),
                ('extra', models.JSONField(blank=True, help_text='Información adicional en JSON (opcional)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='acounts.usuario')),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='acounts_usu_correo_4bf69a_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol', 'estado'], name='acounts_usu_rol_id_539c1b_idx'),
        ),
    ]
